### ISSUE TITLE
Write big picture section

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/docs.ongr.io#6]
Usefull info: https://github.com/nfq-extremes/fox-demo/wiki/Big-Picture

**Comment by mindaugasbarysas** [comment]
Steps: 
1) investigate other projects' big pictures,
2) write skeleton outline
3) add muscles to skeleton.

**Comment by tautrimas** [comment]
Outline will be as follows:

1. Top view server ONGR solution architecture
1. ESB and Filter Manager example
1. Components diagram
1. Sync + Import diagram
1. Other features (Settings bundle, connectors, etc.)

**Comment by saimaz** [comment]
Big picture issue was transfered to https://github.com/ongr-io/global-docs/issues/1
